#pragma once

#include <webgpu/webgpu.hpp>

#include <unordered_map>

using namespace wgpu;

namespace SLGL::Graphics::WebGPU {
    static std::unordered_map<WGPUAdapterType, const char*> wgpuAdapterTypeNames{
            {AdapterType::CPU,           "CPU  - - - - - -"},
            {AdapterType::DiscreteGPU,   "Discrete GPU - -"},
            {AdapterType::IntegratedGPU, "Integrated GPU -"},
    };

    static std::unordered_map<WGPUBackendType, const char*> wgpuBackendTypeNames{
            {BackendType::WebGPU,   "WebGPU - - - - -"},
            {BackendType::D3D11,    "DirectX 11 - - -"},
            {BackendType::D3D12,    "DirectX 12 - - -"},
            {BackendType::Metal,    "Metal  - - - - -"},
            {BackendType::Vulkan,   "Vulkan - - - - -"},
            {BackendType::OpenGL,   "OpenGL - - - - -"},
            {BackendType::OpenGLES, "OpenGLES - - - -"},
    };

    static std::unordered_map<WGPUPresentMode, const char*> wgpuPresentModeNames{
            {PresentMode::Mailbox,     "Mailbox  - - - - Fast Vsync"},
            {PresentMode::FifoRelaxed, "FIFO Relaxed - - Adaptive Vsync"},
            {PresentMode::Fifo,        "FIFO - - - - - - Vsync"},
            {PresentMode::Immediate,   "Immediate  - - - Vsync Off"},
    };

    static std::unordered_map<WGPUTextureFormat, const char*> wgpuTextureFormatNames{
            {TextureFormat::R8Unorm, "R8Unorm"},
            {TextureFormat::R8Snorm, "R8Snorm"},
            {TextureFormat::R8Uint, "R8Uint"},
            {TextureFormat::R8Sint, "R8Sint"},
            {TextureFormat::R16Uint, "R16Uint"},
            {TextureFormat::R16Sint, "R16Sint"},
            {TextureFormat::R16Float, "R16Float"},
            {TextureFormat::RG8Unorm, "RG8Unorm"},
            {TextureFormat::RG8Snorm, "RG8Snorm"},
            {TextureFormat::RG8Uint, "RG8Uint"},
            {TextureFormat::RG8Sint, "RG8Sint"},
            {TextureFormat::R32Float, "R32Float"},
            {TextureFormat::R32Uint, "R32Uint"},
            {TextureFormat::R32Sint, "R32Sint"},
            {TextureFormat::RG16Uint, "RG16Uint"},
            {TextureFormat::RG16Sint, "RG16Sint"},
            {TextureFormat::RG16Float, "RG16Float"},
            {TextureFormat::RGBA8Unorm, "RGBA8Unorm"},
            {TextureFormat::RGBA8UnormSrgb, "RGBA8UnormSrgb"},
            {TextureFormat::RGBA8Snorm, "RGBA8Snorm"},
            {TextureFormat::RGBA8Uint, "RGBA8Uint"},
            {TextureFormat::RGBA8Sint, "RGBA8Sint"},
            {TextureFormat::BGRA8Unorm, "BGRA8Unorm"},
            {TextureFormat::BGRA8UnormSrgb, "BGRA8UnormSrgb"},
            {TextureFormat::RGB10A2Uint, "RGB10A2Uint"},
            {TextureFormat::RGB10A2Unorm, "RGB10A2Unorm"},
            {TextureFormat::RG11B10Ufloat, "RG11B10Ufloat"},
            {TextureFormat::RGB9E5Ufloat, "RGB9E5Ufloat"},
            {TextureFormat::RG32Float, "RG32Float"},
            {TextureFormat::RG32Uint, "RG32Uint"},
            {TextureFormat::RG32Sint, "RG32Sint"},
            {TextureFormat::RGBA16Uint, "RGBA16Uint"},
            {TextureFormat::RGBA16Sint, "RGBA16Sint"},
            {TextureFormat::RGBA16Float, "RGBA16Float"},
            {TextureFormat::RGBA32Float, "RGBA32Float"},
            {TextureFormat::RGBA32Uint, "RGBA32Uint"},
            {TextureFormat::RGBA32Sint, "RGBA32Sint"},
            {TextureFormat::Stencil8, "Stencil8"},
            {TextureFormat::Depth16Unorm, "Depth16Unorm"},
            {TextureFormat::Depth24Plus, "Depth24Plus"},
            {TextureFormat::Depth24PlusStencil8, "Depth24PlusStencil8"},
            {TextureFormat::Depth32Float, "Depth32Float"},
            {TextureFormat::Depth32FloatStencil8, "Depth32FloatStencil8"},
            {TextureFormat::BC1RGBAUnorm, "BC1RGBAUnorm"},
            {TextureFormat::BC1RGBAUnormSrgb, "BC1RGBAUnormSrgb"},
            {TextureFormat::BC2RGBAUnorm, "BC2RGBAUnorm"},
            {TextureFormat::BC2RGBAUnormSrgb, "BC2RGBAUnormSrgb"},
            {TextureFormat::BC3RGBAUnorm, "BC3RGBAUnorm"},
            {TextureFormat::BC3RGBAUnormSrgb, "BC3RGBAUnormSrgb"},
            {TextureFormat::BC4RUnorm, "BC4RUnorm"},
            {TextureFormat::BC4RSnorm, "BC4RSnorm"},
            {TextureFormat::BC5RGUnorm, "BC5RGUnorm"},
            {TextureFormat::BC5RGSnorm, "BC5RGSnorm"},
            {TextureFormat::BC6HRGBUfloat, "BC6HRGBUfloat"},
            {TextureFormat::BC6HRGBFloat, "BC6HRGBFloat"},
            {TextureFormat::BC7RGBAUnorm, "BC7RGBAUnorm"},
            {TextureFormat::BC7RGBAUnormSrgb, "BC7RGBAUnormSrgb"},
            {TextureFormat::ETC2RGB8Unorm, "ETC2RGB8Unorm"},
            {TextureFormat::ETC2RGB8UnormSrgb, "ETC2RGB8UnormSrgb"},
            {TextureFormat::ETC2RGB8A1Unorm, "ETC2RGB8A1Unorm"},
            {TextureFormat::ETC2RGB8A1UnormSrgb, "ETC2RGB8A1UnormSrgb"},
            {TextureFormat::ETC2RGBA8Unorm, "ETC2RGBA8Unorm"},
            {TextureFormat::ETC2RGBA8UnormSrgb, "ETC2RGBA8UnormSrgb"},
            {TextureFormat::EACR11Unorm, "EACR11Unorm"},
            {TextureFormat::EACR11Snorm, "EACR11Snorm"},
            {TextureFormat::EACRG11Unorm, "EACRG11Unorm"},
            {TextureFormat::EACRG11Snorm, "EACRG11Snorm"},
            {TextureFormat::ASTC4x4Unorm, "ASTC4x4Unorm"},
            {TextureFormat::ASTC4x4UnormSrgb, "ASTC4x4UnormSrgb"},
            {TextureFormat::ASTC5x4Unorm, "ASTC5x4Unorm"},
            {TextureFormat::ASTC5x4UnormSrgb, "ASTC5x4UnormSrgb"},
            {TextureFormat::ASTC5x5Unorm, "ASTC5x5Unorm"},
            {TextureFormat::ASTC5x5UnormSrgb, "ASTC5x5UnormSrgb"},
            {TextureFormat::ASTC6x5Unorm, "ASTC6x5Unorm"},
            {TextureFormat::ASTC6x5UnormSrgb, "ASTC6x5UnormSrgb"},
            {TextureFormat::ASTC6x6Unorm, "ASTC6x6Unorm"},
            {TextureFormat::ASTC6x6UnormSrgb, "ASTC6x6UnormSrgb"},
            {TextureFormat::ASTC8x5Unorm, "ASTC8x5Unorm"},
            {TextureFormat::ASTC8x5UnormSrgb, "ASTC8x5UnormSrgb"},
            {TextureFormat::ASTC8x6Unorm, "ASTC8x6Unorm"},
            {TextureFormat::ASTC8x6UnormSrgb, "ASTC8x6UnormSrgb"},
            {TextureFormat::ASTC8x8Unorm, "ASTC8x8Unorm"},
            {TextureFormat::ASTC8x8UnormSrgb, "ASTC8x8UnormSrgb"},
            {TextureFormat::ASTC10x5Unorm, "ASTC10x5Unorm"},
            {TextureFormat::ASTC10x5UnormSrgb, "ASTC10x5UnormSrgb"},
            {TextureFormat::ASTC10x6Unorm, "ASTC10x6Unorm"},
            {TextureFormat::ASTC10x6UnormSrgb, "ASTC10x6UnormSrgb"},
            {TextureFormat::ASTC10x8Unorm, "ASTC10x8Unorm"},
            {TextureFormat::ASTC10x8UnormSrgb, "ASTC10x8UnormSrgb"},
            {TextureFormat::ASTC10x10Unorm, "ASTC10x10Unorm"},
            {TextureFormat::ASTC10x10UnormSrgb, "ASTC10x10UnormSrgb"},
            {TextureFormat::ASTC12x10Unorm, "ASTC12x10Unorm"},
            {TextureFormat::ASTC12x10UnormSrgb, "ASTC12x10UnormSrgb"},
            {TextureFormat::ASTC12x12Unorm, "ASTC12x12Unorm"},
            {TextureFormat::ASTC12x12UnormSrgb, "ASTC12x12UnormSrgb"},
//            {TextureFormat::R16Unorm, "R16Unorm"},
//            {TextureFormat::RG16Unorm, "RG16Unorm"},
//            {TextureFormat::RGBA16Unorm, "RGBA16Unorm"},
//            {TextureFormat::R16Snorm, "R16Snorm"},
//            {TextureFormat::RG16Snorm, "RG16Snorm"},
//            {TextureFormat::RGBA16Snorm, "RGBA16Snorm"},
//            {TextureFormat::R8BG8Biplanar420Unorm, "R8BG8Biplanar420Unorm"},
//            {TextureFormat::R10X6BG10X6Biplanar420Unorm, "R10X6BG10X6Biplanar420Unorm"},
//            {TextureFormat::R8BG8A8Triplanar420Unorm, "R8BG8A8Triplanar420Unorm"},
//            {TextureFormat::R8BG8Biplanar422Unorm, "R8BG8Biplanar422Unorm"},
//            {TextureFormat::R8BG8Biplanar444Unorm, "R8BG8Biplanar444Unorm"},
//            {TextureFormat::R10X6BG10X6Biplanar422Unorm, "R10X6BG10X6Biplanar422Unorm"},
//            {TextureFormat::R10X6BG10X6Biplanar444Unorm, "R10X6BG10X6Biplanar444Unorm"},
    };

    void DebugPrintAdapter(Adapter& adapter);
    void DebugPrintPresentMode(WGPUPresentMode presentMode);
    void DebugPrintSurfaceFormat(WGPUTextureFormat textureFormat);
    void DebugPrintImplementation();

}